apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: web-app-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: web-app
  
  minReplicas: 2 # Минимум 2 реплики ночью для отказоустойчивости
  maxReplicas: 6 # Максимум 6 реплик днем для обработки пиковой нагрузки
  
  # Метрики для автомасштабирования
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60 # Целевая утилизация CPU 60%
  
  behavior:
    # Настройки масштабирования вверх
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Pods
        value: 1
        periodSeconds: 60
      - type: Percent
        value: 100
        periodSeconds: 60
      selectPolicy: Max
    
    # Настройки масштабирования вниз (более консервативные)
    scaleDown:
      stabilizationWindowSeconds: 300 # Длинное окно для избежания флуктуаций
      policies:
      - type: Pods
        value: 1
        periodSeconds: 300
      selectPolicy: Max
